spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ik_management
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog-master.xml
    enabled: true