CREATE TABLE departments
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                             NOT NULL,
    location   VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    CONSTRAINT pk_departments PRIMARY KEY (id)
);

CREATE TABLE employee_projects
(
    employee_id BIGINT NOT NULL,
    project_id  BIGINT NOT NULL,
    CONSTRAINT pk_employee_projects PRIMARY KEY (employee_id, project_id)
);

CREATE TABLE employees
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name    VARCHAR(255)                             NOT NULL,
    last_name     VARCHAR(255)                             NOT NULL,
    email         VARCHAR(255)                             NOT NULL,
    phone_number  VARCHAR(20),
    hire_date     TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    job_title     VARCHAR(255),
    department_id INTEGER,
    user_id       INTEGER,
    CONSTRAINT pk_employees PRIMARY KEY (id)
);

CREATE TABLE projects
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255)                             NOT NULL,
    description   TEXT,
    start_date    TIMESTAMP WITHOUT TIME ZONE              NOT NULL,
    end_date      TIMESTAMP WITHOUT TIME ZONE,
    department_id INTEGER,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username   VARCHAR(255)                             NOT NULL,
    email      VARCHAR(255)                             NOT NULL,
    password   VARCHAR(255)                             NOT NULL,
    role       VARCHAR(50),
    created_at BYTEA                                    NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE departments
    ADD CONSTRAINT uc_departments_name UNIQUE (name);

ALTER TABLE employees
    ADD CONSTRAINT uc_employees_email UNIQUE (email);

ALTER TABLE employees
    ADD CONSTRAINT uc_employees_user UNIQUE (user_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE employees
    ADD CONSTRAINT FK_EMPLOYEES_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES departments (id);

ALTER TABLE employees
    ADD CONSTRAINT FK_EMPLOYEES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE employee_projects
    ADD CONSTRAINT FK_EMPLOYEE_PROJECTS_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id);

ALTER TABLE employee_projects
    ADD CONSTRAINT FK_EMPLOYEE_PROJECTS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE projects
    ADD CONSTRAINT FK_PROJECTS_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES departments (id);